npop: 200                   #Number of particles 
nbunches: 100                       #Number of bunches
gap: 0
# Arrival time in picoseconds (ps)
tau:
  prob_dist: Gauss
  mu: 0
  sigma: 3
# normalized momentum deviation (unitless)
delta:
  prob_dist: Gauss
  mu: 0
  sigma: 1
#  mu: 0
#  sigma: 3
# transverse position
x_trans:
  prob_dist: Gauss
  mu: 0
  sigma: 1
# transverse momentum
px_trans:
  prob_dist: Gauss
  mu: 0
  sigma: 1