# we define some parameters that are shared between all coordinates
npop: 2000                       # Number of simulation particles 
nRealPerSim: 1                   # Number of real particles per simulation particle (used in wakefield calculation)
nbunches: 1320                   # Number of bunches
gap: 0                           # the number of bunches that are empty at the end
# The format here is that for each coordinate (all 6 of them), we define a probability distribution as well as its associated parameters.
# All distributions should have a lower and upper attribute defined

#Currently, only the following are implemented:
#  - Guassians
#    - Parameters: Sigma, Mu
#  - Quartic potential (ie. equillibrium density of the form exp(-a \tau^2)
#    - Parameters: Constant
tau:                             # Arrival time in picoseconds (ps)
  prob_dist: Gauss
  mu: 0
  sigma: 30 
  lower: -100 
  upper: 100
delta:                           # normalized momentum deviation (unitless)
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
x_trans:                         # transverse x position
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
px_trans:                        # transverse x momentum
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
y_trans:                        # transverse y position
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
py_trans:                       # transverse  y momentum
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
