npop: 2000                   #Number of particles 
nbunches: 100                      #Number of bunches
gap: 0
# Arrival time in picoseconds (ps)
tau:
  prob_dist: Gauss
  mu: 0
  sigma: 30 
  lower: -100 
  upper: 100
# normalized momentum deviation (unitless)
delta:
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
# transverse position
x_trans:
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
# transverse momentum
px_trans:
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
