npop: 20000                       #Number of particles 
nRealPerSim: 1
nbunches: 1320                      #Number of bunches
gap: 0
# Arrival time in picoseconds (ps)
tau:
  prob_dist: Gauss
  mu: 0
  sigma: 30 
  lower: -100 
  upper: 100
# normalized momentum deviation (unitless)
delta:
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
# transverse x position
x_trans:
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
# transverse x momentum
px_trans:
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
# transverse y position
y_trans:
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
# transverse  y momentum
py_trans:
  prob_dist: Gauss
  mu: 0
  sigma: 1
  lower: -5
  upper: 5
