E0: 3d9                   # Reference particle energy in (eV)
vrf: 3.6d6                # Reference voltage of main cavity (eV)
nharm: 1320               # Harmonic number of main cavity
f0: 378545.45            # base rf frequency of ring in Hz (multiply by 2pi for angular frequency)
Aver_curr: 0.5d0          # Average current of beam
gap: 0                    # RF bucket gap (lattice)
sig_d: 7.88d-4            # Momentum spread of detector
alpha_C: 5.951d-5         # momentum compaction
x_betatron_tune: 1.0      # betatron tune of transverse x direction
x_lin_chromaticity: 1.0   # linear chromaticity in x direction
Uloss: 6.74d5             # Energy loss per turn (eV)
rjs: 1.81d0               # longitudinal rad partition number
