nturns: 10    # Number of turns for the simulation
kon: 100        # Number of turns radiation damping is artifically scaled (unused)
frad: 1d0       # scaling factor of radiation damping for first kon turns (unused)
nturnon: 200    # Turn on beam loading compensation after nturnon turns (unused)
nhist: 1        # Number of turns back in history you need to look back (unused)
alpha_tau: 1    # Radiation damping constant in tau (1/s)
Dis_tau: 1      # Dispersion constant in tau  
alpha_x: 1      # Radiation damping constant in x (1/s)
Dis_x: 1        # Dispersion constant in x 
alpha_y: 1      # Radiation damping constant in x (1/s)
Dis_y: 1        # Dispersion constant in x 