rangetau: 4 # Longitudinal grid size (in picoseconds)
# Wakefield data files (tau should be in units of picoseconds.  Y is in arbitray units?)
TauWakeFile: ../configs/TauWakefield.csv
XWakeFile: ../configs/XWakefield.csv
YWakeFile: ../configs/YWakefield.csv
FourierCoeff: 50  # Number of fourier coefficient in long distance calculation (unused)
